require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DialogsController do

  def mock_dialog(stubs={})
    @mock_dialog ||= mock_model(Dialog, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all dialogs as @dialogs" do
      Dialog.stub(:all) { [mock_dialog] }
      get :index
      assigns(:dialogs).should eq([mock_dialog])
    end
  end

  describe "GET show" do
    it "assigns the requested dialog as @dialog" do
      Dialog.stub(:find).with("37") { mock_dialog }
      get :show, :id => "37"
      assigns(:dialog).should be(mock_dialog)
    end
  end

  describe "GET new" do
    it "assigns a new dialog as @dialog" do
      Dialog.stub(:new) { mock_dialog }
      get :new
      assigns(:dialog).should be(mock_dialog)
    end
  end

  describe "GET edit" do
    it "assigns the requested dialog as @dialog" do
      Dialog.stub(:find).with("37") { mock_dialog }
      get :edit, :id => "37"
      assigns(:dialog).should be(mock_dialog)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created dialog as @dialog" do
        Dialog.stub(:new).with({'these' => 'params'}) { mock_dialog(:save => true) }
        post :create, :dialog => {'these' => 'params'}
        assigns(:dialog).should be(mock_dialog)
      end

      it "redirects to the created dialog" do
        Dialog.stub(:new) { mock_dialog(:save => true) }
        post :create, :dialog => {}
        response.should redirect_to(dialog_url(mock_dialog))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dialog as @dialog" do
        Dialog.stub(:new).with({'these' => 'params'}) { mock_dialog(:save => false) }
        post :create, :dialog => {'these' => 'params'}
        assigns(:dialog).should be(mock_dialog)
      end

      it "re-renders the 'new' template" do
        Dialog.stub(:new) { mock_dialog(:save => false) }
        post :create, :dialog => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dialog" do
        Dialog.stub(:find).with("37") { mock_dialog }
        mock_dialog.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :dialog => {'these' => 'params'}
      end

      it "assigns the requested dialog as @dialog" do
        Dialog.stub(:find) { mock_dialog(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:dialog).should be(mock_dialog)
      end

      it "redirects to the dialog" do
        Dialog.stub(:find) { mock_dialog(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(dialog_url(mock_dialog))
      end
    end

    describe "with invalid params" do
      it "assigns the dialog as @dialog" do
        Dialog.stub(:find) { mock_dialog(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:dialog).should be(mock_dialog)
      end

      it "re-renders the 'edit' template" do
        Dialog.stub(:find) { mock_dialog(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dialog" do
      Dialog.stub(:find).with("37") { mock_dialog }
      mock_dialog.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the dialogs list" do
      Dialog.stub(:find) { mock_dialog }
      delete :destroy, :id => "1"
      response.should redirect_to(dialogs_url)
    end
  end

end
